language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

env:
  - SYMFONY_VERSION="2.2.x"
  - SYMFONY_VERSION="2.3.x"
  - SYMFONY_VERSION="2.4.x"
  - SYMFONY_VERSION="2.5.x-dev symfony/debug:2.5.x-dev symfony/event-dispatcher:2.5.x-dev symfony/http-kernel:2.5.x-dev"

before_script:
  - composer require symfony/framework-bundle:${SYMFONY_VERSION} --dev --no-update
  - composer install
