language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  include:
    - php: 5.5
      env: SYMFONY_VERSION="2.3.x"
    - php: 5.5
      env: SYMFONY_VERSION="2.4.x"
    - php: 5.5
      env: SYMFONY_VERSION="2.5.x"
    - php: 5.5
      env: SYMFONY_VERSION="2.6.x@dev"

before_script:
  - sh -c 'if [ "$SYMFONY_VERSION" != "" ]; then composer require symfony/symfony:${SYMFONY_VERSION} --dev --no-update; fi'
  - composer install

script:
  - phpunit --coverage-clover=coverage.clover
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi'
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi'
