sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - SYMFONY_VERSION=""
    - deps=""

matrix:
  fast_finish: true
  include:
    - php: 5.3
    - php: 5.3
      env: deps="low"
    - php: 5.4
    - php: 5.5
    - php: 5.6
      env: SYMFONY_VERSION="2.3.x"
    - php: 5.6
      env: SYMFONY_VERSION="2.6.x"
    - php: 5.6
      env: SYMFONY_VERSION="2.7.x"
    - php: 5.6
      env: SYMFONY_VERSION="2.8.x@dev"
    - php: 7.0
    - php: hhvm
  allow_failures:
    - php: hhvm

before_install:
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require symfony/symfony:${SYMFONY_VERSION} --dev --no-update; fi

install:
  - if [ "$deps" = "" ]; then composer install; fi
  - if [ "$deps" = "low" ]; then composer update --prefer-lowest; fi

script:
  - phpunit --coverage-clover=coverage.clover

after_script:
  # PHP 7.0 and HHVM 3.5 are not able to generate code coverage
  # Avoid notifying that generating it failed to let other jobs upload it rather than  cancelling the Scrutinizer job
  - if [[ "$TRAVIS_PHP_VERSION" != "7.0" && "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
