sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  global:
    - COMPOSER_OPTIONS="--prefer-stable"
    - SYMFONY_VERSION=""

matrix:
  fast_finish: true
  include:
    - php: 5.3
      env: COMPOSER_OPTIONS="--prefer-lowest --prefer-stable"
    - php: 5.4
    - php: 5.5
    - php: 5.6
      env: SYMFONY_VERSION="2.7.x"
    - php: 5.6
      env: SYMFONY_VERSION="2.8.x"
    - php: 5.6
      env: SYMFONY_VERSION="3.1.x"
    - php: 7.0
      env: xdebug=yes COMPOSER_OPTIONS=""
    - php: hhvm

before_install:
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then echo memory_limit = -1 >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" && "$xdebug" != "yes" ]]; then phpenv config-rm xdebug.ini; fi
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require symfony/symfony:${SYMFONY_VERSION} --dev --no-update; fi

install:
  - composer update $COMPOSER_OPTIONS

script:
  - if [[ "$xdebug" = "yes" ]]; then phpunit --coverage-clover=coverage.clover; else phpunit; fi

after_script:
  - if [[ "$xdebug" = "yes" ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ "$xdebug" = "yes" ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
